Repository lunarway/release-manager, pull requests merged in 2022-10, with the labels that each got.

#444 Publish ReleaseSucceeded event when daemon reports success
  Makefile
  cmd/server/command/start.go
  internal/events/release_succeeded.go
  internal/flow/flow.go
  internal/flow/notify.go
  internal/slack/slack.go
Labels: minor

#450 Make sure we don't crash on missing email
  cmd/hamctl/command/policy.go
  cmd/hamctl/command/root.go
  cmd/hamctl/command/root_test.go
Labels: patch

#449 Update external go packages
  go.mod
  go.sum
Labels: dependencies
