Repository lunarway/release-manager, pull requests merged in 2022-11, with the labels that each got.

#452 Update golang Docker tag to v1.19.3
  Dockerfile-daemon
  Dockerfile-server
Labels: dependencies

#451 Update module github.com/aws/aws-sdk-go to v1.44.128
  go.mod
  go.sum
Labels: dependencies

#453 Update external go packages
  go.mod
  go.sum
Labels: dependencies

#454 Add release failed event
  Dockerfile-server
  cmd/server/command/start.go
  internal/events/release_failed.go
  internal/flow/flow.go
  internal/flow/notify.go
  internal/http/types.go
  internal/slack/slack.go
Labels: minor

#456 Update external go packages
  go.mod
  go.sum
Labels: dependencies

#459 Update alpine Docker tag to v3.17.0
  Dockerfile-daemon-goreleaser
  Dockerfile-server
  Dockerfile-server-goreleaser
Labels: dependencies

#461 Fixed event types and added tests
  internal/events/release_event_test.go
  internal/events/release_failed.go
  internal/events/release_failed_test.go
  internal/events/release_succeeded.go
  internal/events/release_suceeded_test.go
  internal/events/released_event.go
Labels: patch
