Repository lunarway/release-manager, pull requests merged in 2023-08, with the labels that each got.

#486 Added commit message to author release slack message
  internal/slack/slack.go
Labels: minor

#487 Removed replacements as it is not allowed anymore
  .goreleaser.yml
Labels: patch

#488 Update golang Docker tag to v1.20.7
  Dockerfile-daemon
  Dockerfile-server
Labels: dependencies

#489 Update alpine Docker tag to v3.18.3
  Dockerfile-daemon-goreleaser
  Dockerfile-server
  Dockerfile-server-goreleaser
Labels: dependencies

#490 Update golang Docker tag to v1.21.0
  Dockerfile-daemon
  Dockerfile-server
Labels: dependencies
