Repository lunarway/release-manager, pull requests merged in 2024-08, with the labels that each got.

#542 Update golang Docker tag to v1.22.6
  .github/workflows/build.yml
  .github/workflows/release.yml
  Dockerfile-daemon
  Dockerfile-server
Labels: dependencies

#543 Update golang Docker tag to v1.23.0
  .github/workflows/build.yml
  .github/workflows/release.yml
  Dockerfile-daemon
  Dockerfile-server
Labels: dependencies

#544 Added environmnet to deployment annotation
  cmd/server/command/start.go
Labels: minor

#545 Fix go releaser
  .github/workflows/release-check.yml
  .github/workflows/release.yml
  .goreleaser.yml
Labels: patch
