Repository lunarway/release-manager, pull requests merged in 2024-01, with the labels that each got.

#512 Update goreleaser/goreleaser-action action to v5
  .github/workflows/release.yml
Labels: dependencies

#515 Bump go version for release job
  .github/workflows/release.yml
Labels: patch

#516 Print login required output when token is expired
  internal/http/authenticator.go
  internal/http/client.go
Labels: patch

#518 Update golang Docker tag to v1.21.6
  Dockerfile-daemon
  Dockerfile-server
Labels: dependencies

#521 store access token
  internal/http/authenticator.go
Labels: patch

#523 Update actions/cache action to v4
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: dependencies

#524 Update module github.com/lestrrat-go/jwx/v2 to v2.0.19 [SECURITY]
  go.mod
  go.sum
Labels: security

#525 Update alpine Docker tag to v3.19.1
  Dockerfile-daemon-goreleaser
  Dockerfile-server
  Dockerfile-server-goreleaser
Labels: dependencies
