Repository lunarway/release-manager, pull requests merged in 2024-03, with the labels that each got.

#528 Update golang Docker tag to v1.22.1
  Dockerfile-daemon
  Dockerfile-server
Labels: dependencies

#530 Add squad to release notifications
  cmd/artifact/Makefile
  cmd/artifact/command/init.go
  cmd/server/command/start.go
  internal/metrics/metrics.go
Labels: minor

#529 Update module github.com/lestrrat-go/jwx/v2 to v2.0.21 [SECURITY]
  go.mod
  go.sum
Labels: security

#531 Fix OOMKilled check and update OOMKilled log
  cmd/daemon/kubernetes/pods.go
  cmd/daemon/kubernetes/pods_test.go
Labels: patch
